services:
  app: &app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      HISTFILE: /app/.local/.bash_history
    volumes:
      - nfsmount:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :${PWD}
