FROM golang:1.17-alpine AS builder

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY *.go ./
RUN go build

FROM alpine

# WORKDIR /app
COPY --from=builder /app/golovina /app

EXPOSE 3000

CMD /app
