
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mint
  password: mint

development:
  <<: *default
  database: mint_development

test:
  <<: *default
  database: mint_test

production:
  <<: *default
  database: mint_production
