default: &default
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:postgres@localhost/golovina-dev") %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 15) %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_TEST_URL", "postgres://postgres:postgres@localhost/golovina-test") %>

production: &production
  <<: *default
