# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
filter = { only_tables = ["users", "delivery_cities", "categories", "category_translations", "orders", "order_items", "themes", "theme_translations", "variants", "wishlists"] }
