FROM rust:1.62-alpine AS builder

ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk update && apk add bash gcc g++ build-base libc-dev libpq libpq-dev vips vips-dev

WORKDIR /app
COPY . .
RUN cargo build --release

FROM alpine
RUN apk update && apk add bash gcc
COPY --from=builder /app/target/release/golovina-fastapi /app

EXPOSE 3000

CMD /app
