require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - app/commands/**/*.rb
    - app/contracts/**/*.rb
    - app/controllers/api/**/*.rb
    - app/jobs/**/*.rb
    - app/models/api/**/*.rb
    - app/policies/api/**/*.rb
    - app/views/api/**/*.rb
    - spec/commands/**/*.rb
    - spec/contracts/**/*.rb
    - spec/jobs/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

NestedGroups:
  Max: 4

# Style/ClassAndModuleChildren:
#   EnforcedStyle: compact

# Style/FrozenStringLiteralComment:
#   Enabled: false

# Style/Documentation:
#   Enabled: false

# Layout/ArgumentAlignment:
#   EnforcedStyle: with_fixed_indentation

# Metrics/MethodLength:
#   Max: 15

# Metrics/LineLength:
#   Max: 90

# Metrics/BlockLength:
#   ExcludedMethods: ['describe', 'context', 'enum', 'feature']
