# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", "~> 6.1"

gem "pg", "~> 1.0"
gem "puma", "~> 5.6"

gem "jwt"

gem "mjml-rails"
gem "slim-rails"

gem "friendly_id"

gem "aws-sdk-s3", require: false
gem "carrierwave"
gem "fog-aws"
gem "image_processing"
gem "mini_magick"
gem "streamio-ffmpeg"

gem "figaro"

gem "faraday"
gem "faraday_middleware"

gem "meta-tags"

gem "redcarpet"

gem "addressable"

gem "devise"
gem "jwt"
gem "pundit"

gem "dry-validation"
gem "service_actor-rails"

gem "globalize"
gem "globalize-accessors"
gem "i18n-js"
gem "rails-i18n"

gem "enum_help"
gem "stateful_enum"

gem "hiredis"
gem "sidekiq"
gem "sidekiq-scheduler"

gem "react-rails"
gem "webpacker"

gem "jb"
gem "jbuilder"
gem "jsonapi-serializer"
gem "oj"

gem "sitemap_generator"

gem "bootsnap", require: false

gem "elasticsearch-model"
gem "elasticsearch-rails"
gem "elasticsearch-ruby"

gem "bugsnag"
gem "newrelic_rpm"

gem "amazing_print"
gem "rails_semantic_logger"

group :development, :test do
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-json_expectations"
  gem "rspec-rails"
  gem "webmock"
  # gem 'mock_redis'

  # TODO: remove it
  gem "rails-controller-testing"
  gem "shoulda-matchers"
end

group :development do
  gem "listen"
  # gem 'web-console'

  gem "spring"
  # gem 'spring-watcher-listen'

  gem "letter_opener"

  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
