source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.1'

gem 'pg', '~> 1.0'
gem 'puma', '~> 5.6'

gem 'mjml-rails'
gem 'slim-rails'

gem 'friendly_id'

gem 'aws-sdk-s3', require: false
gem 'carrierwave'
gem 'fog-aws'
gem 'mini_magick'
gem 'streamio-ffmpeg'
gem 'image_processing'

gem 'figaro'

gem 'meta-tags'

gem 'redcarpet'

gem 'addressable'

gem 'devise'
gem 'jwt'
gem 'pundit'

gem "service_actor-rails"
gem 'dry-validation'

gem 'globalize'
gem 'globalize-accessors'
gem 'i18n-js'
gem 'rails-i18n'

gem 'enum_help'
gem 'stateful_enum'

gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'hiredis'

gem 'react-rails'
gem 'webpacker'

gem 'jbuilder'
gem 'jb'
gem 'jsonapi-serializer'

gem 'sitemap_generator'

gem 'bootsnap', require: false

gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'elasticsearch-ruby'

gem 'bugsnag'

gem 'amazing_print'
gem 'rails_semantic_logger'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'webmock'
  # gem 'mock_redis'

  # TODO: remove it
  gem 'shoulda-matchers'
  gem 'rails-controller-testing'
end

group :development do
  gem 'listen'
  # gem 'web-console'

  gem 'spring'
  # gem 'spring-watcher-listen'

  gem 'letter_opener'

  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end
