source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.0.0'

gem 'pg', '~> 1.0'
gem 'puma', '~> 5.5'

gem 'slim-rails'

gem 'friendly_id'

gem 'aws-sdk-s3', require: false
gem 'carrierwave'
gem 'fog-aws'
gem 'mini_magick'
gem 'streamio-ffmpeg'

gem 'meta-tags'

gem 'redcarpet'

gem 'addressable'

gem 'devise'
gem 'jwt'
gem 'pundit'

gem 'globalize'
gem 'globalize-accessors'
gem 'i18n-js'
gem 'rails-i18n'

gem 'enum_help'
gem 'stateful_enum'

gem 'sidekiq'

gem 'react-rails'
gem 'webpacker'

gem 'jbuilder'
gem 'jsonapi-serializer'

gem 'sitemap_generator'

gem 'bootsnap', require: false

gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'elasticsearch-ruby'

gem 'bugsnag'

group :development, :test do
  # gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  gem 'rspec-rails'

  gem 'rails-controller-testing'

  gem 'capybara'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'shoulda-matchers'
  # gem 'capybara-screenshot'
  # gem 'selenium-webdriver'

  gem 'webdrivers'
end

group :development do
  gem 'listen'
  gem 'web-console'

  gem 'spring'
  gem 'spring-watcher-listen'

  gem 'letter_opener'

  gem 'rubocop-rails', require: false

  gem 'capistrano', require: false
  gem 'capistrano-passenger', require: false
  gem 'capistrano-rails', require: false
  gem 'capistrano-rbenv', require: false
end
