name: CD

# on:
#   release:
#     types: [published]

on: push

jobs:
  # build-and-push-api-image:
  #   needs: dockerhub
  #   runs-on: ubuntu-latest

  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: golovina
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432

  #   steps:
  #     - uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - uses: actions/checkout@v2
  #     - uses: docker/build-push-action@v2
  #       with:
  #         context: ./api
  #         file: ./api/Dockerfile.k8s
  #         build-args: |
  #           APP_VERSION=${{ github.event.release.tag_name }}
  #         push: true
  #         tags: |
  #           bragovo/golovina-api:${{ github.event.release.tag_name }}
  #           bragovo/golovina-api:latest

  build-and-push-fastapi-image:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
        with:
          context: ./fastapi-rs
          file: ./fastapi-rs/Dockerfile.k8s
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            bragovo/golovina-fastapi-rs:latest

  # build-and-push-app-image:
  #   needs: dockerhub
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - uses: actions/checkout@v2
  #     - uses: docker/build-push-action@v2
  #       with:
  #         context: ./app
  #         file: ./app/Dockerfile.k8s
  #         build-args: |
  #           NEXT_PUBLIC_API_URL=/api
  #           NEXT_PUBLIC_BUGSNAG_API_KEY=${{ secrets.NEXT_PUBLIC_BUGSNAG_API_KEY }}
  #           NEXT_PUBLIC_APPLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_APPLE_CLIENT_ID }}
  #           NEXT_PUBLIC_APPLE_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_APPLE_REDIRECT_URI }}
  #           NEXT_PUBLIC_PAYKEEPER_GAYEWAY=${{ secrets.NEXT_PUBLIC_PAYKEEPER_GAYEWAY }}
  #         push: true
  #         tags: |
  #           bragovo/golovina-app:${{ github.event.release.tag_name }}
  #           bragovo/golovina-app:latest

