name: Build Image

on:
  push:
    branches:
      - cd

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

  build-and-push-api-image:
    needs: dockerhub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile.k8s
          push: true
          tags: |
            bragovo/golovina-api:latest
          # bragovo/golovina-api:${{ github.event.release.tag_name }}
